# Default values for postgres-image.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

project_id: "" # Mapped by fasit

image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/postgres-image
  pullPolicy: IfNotPresent
  tag: latest
